Add new documentation
open-source-uc/osuc-template pull request #8
Opened 2022-09-08 16:44 UTC by diegocostares

# Problema

Habían cosas que faltaba explicar, hay links sin actualizar y faltan cosas en el gitignore.

## Solución

Lista con soluciones implementadas.
- Modifique un poco las templates de las issues y PR
- Agregue nuevas cosas al `.gitignore`
- Cambie bastante el `readme.md`
- Actualice la licencia para el 2022
- Agregue mayor documentación al archivo `conducting.md`, haciendo más fácil de leer el workflow y poniendo un tutorial con los comandos típicos.

2022-09-16 20:09 UTC, diegocostares commented
@agucova @benjavicente

2022-09-16 20:29 UTC, benjavicente requested changes
No soy fan de mantener este templete, así que plz no me etiquetes para pedir reviews 😅

De todas formas, esto es lo que encontré:

2022-09-16 20:29 UTC, benjavicente commented on contributing.md
> +git remote add upstream https://github.com/stevemao/REPOSITORY-NAME
`stevemao`?

2022-09-16 20:29 UTC, benjavicente commented on contributing.md
> +```
Hay una mezcla de español e inglés.

No entendí a que se refiere a lo último de la tabla 🤔

2022-09-16 20:29 UTC, benjavicente commented on README.md
> +  <a href="#Licencía">Licencía</a>
```suggestion
  <a href="#Licencía">Licencia</a>
```

Le pasaría un corrector ortográfico para revisar los typos

2022-09-16 20:29 UTC, benjavicente commented on README.md
> +### Resolución de problemas
Estos títulos quedan raros si no tienen un cuerpo de referencia.

2022-10-28 19:30 UTC, diegocostares commented
@benjavicente Arregle lo que me dijiste y aproveche de dejar subido un workflow de flake8

2022-10-29 15:41 UTC, benjavicente approved these changes

2022-11-12 02:33 UTC, merged